$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql -e "create user 'javauser'@'%' identified by 'pass';"
  SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "mysqldb" do |mysqldb|

    config.vm.network "public_network", ip: "192.168.50.4"

    config.vm.provision "shell",
      inline: "cat /configs/ssh-key.pub >> .ssh/authorized_keys"

    config.vm.provision "shell",
      inline: $script_mysql

    config.vm.provision "shell",
      inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"

    config.vm.provision "shell",
      inline: "service mysql restart"

    config.vm.synced_folder "C:/desenvolvimento/devops/ambiente-dev/bionic/configs" , "/configs"
    config.vm.synced_folder ".", "/vagrant", disable: true

  end
  config.vm.define "phpweb" do |phpweb|

    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb.vm.network "public_network", ip: "192.168.50.5"

    phpweb.vm.provision "shell",
            inline: "apt-get update && apt-get install -y puppet"

    phpweb.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./configs/manifests"
        puppet.manifest_file = "phpweb.pp"
      end
  end
  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "192.168.50.6"
    mysqlserver.vm.provision "shell",
      inline: "cat vagrant/configs/ssh-key.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.50.7"

    ansible.vm.provision "shell",
      inline: "cp /vagrant/id_bionic  /home/vagrant && \
              chmod 600 /home/vagrant/ssh-key && \
              chown vagrant:vagrant /home/vagrant/ssh-key"

    ansible.vm.provision "shell",
      inline: "apt-get update && \
               apt-get install -y software-properties-common && \
               apt-add-repository --yes --update ppa:ansible/ansible && \
               apt-get install -y ansible"

     ansible.vm.provision "shell",
       inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                  /vagrant/configs/ansible/playbook.yml"
  end
end
